
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int cadena = 23;
  public static final int coma = 9;
  public static final int numero = 22;
  public static final int saltolinea = 13;
  public static final int llaveabre = 2;
  public static final int comilladoble = 11;
  public static final int comillaAbrir = 14;
  public static final int porcentaje = 7;
  public static final int conj = 21;
  public static final int positivo = 20;
  public static final int comillasimple = 12;
  public static final int guion = 4;
  public static final int disyuncion = 18;
  public static final int comillaCerrar = 15;
  public static final int EOF = 0;
  public static final int letra = 25;
  public static final int id = 24;
  public static final int error = 1;
  public static final int llavecierra = 3;
  public static final int tilde = 6;
  public static final int interrogacion = 19;
  public static final int concatenacion = 16;
  public static final int kleene = 17;
  public static final int dospuntos = 8;
  public static final int puntoycoma = 10;
  public static final int mayor = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "llaveabre",
  "llavecierra",
  "guion",
  "mayor",
  "tilde",
  "porcentaje",
  "dospuntos",
  "coma",
  "puntoycoma",
  "comilladoble",
  "comillasimple",
  "saltolinea",
  "comillaAbrir",
  "comillaCerrar",
  "concatenacion",
  "kleene",
  "disyuncion",
  "interrogacion",
  "positivo",
  "conj",
  "numero",
  "cadena",
  "id",
  "letra"
  };
}

